anchor_version = "0.13.2"

[workspace]
members = ["program"]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
token_vesting = "FhNbZ87io3fvp3f9Q3ggeJLQhNTEPCsuoW8SS1xJYzeN"
